### ISSUE TITLE
Node list

### ISSUE THREAD

**Issue by kesior** [SadBatman/sumowallet#13]
When more nodes appear that are public, recommend adding a small pulldown list for easier choice - or, a button that will allow for a custom node to be entered. Updating the list from a text file, once a month or at a random time?

**Comment by SadBatman** [comment]
That's the current logic. The node input field actually shows a list a combination of:

- A list of nodes included in the app. This list has the size of 1 right now :)
- Any other node that the user provided (these are stored in prefs)
