### ISSUE TITLE
"Unfortunately, System UI has stopped."

### ISSUE THREAD

**Issue by Sourpusss** [SadBatman/sumowallet#7]
This error occurs repeatedly while I've been attempting to recover my wallet on my phone, after using the seed recovery option.  This message pops up on my LOCKSCREEN with an "ok" option attached.  When pressed, the phone moves from the erromessage / lockscreen to a blue background (assumedly a wallet asset, but one I haven't seen while using the wallet up until this point).  After the blue background is shown for about a half second, the screen displays a syncing page, with all the progress sections at 0.  This page actively moves (the "connecting (please wait)" bar cycles) for another half a second, then it all returns back to the original error/lockscreen.

After messing with this loop for a while, I tried to exit the program, but nothing works. Manually locking and unlocking causes the error to be at the top still, and pressing the home button (or holding it to bring up the task manager) has no effect.  The only option seems to be holding the lock button to bring up the power menu, and manually shutting down.  Unfortunately, pressing the restart option in the power menu has no effect, and only "shut down" seems to do anything.  Otherwise it just keeps looping due to screen input.

I am running this on android, with a galaxy note 3.

**Comment by SadBatman** [comment]
Can you make screenshots ?  Do you use a custom launcher?

**Comment by sumogr** [comment]
https://android-fix.com/android-errors/41-unfortunately-system-ui-has-stopped.html

**Comment by SadBatman** [comment]
Please reopen when you have more info.
