### ISSUE TITLE
If you have Monerujo installed...you can't install the prebuilt APKs of Sumo Wallet

### ISSUE THREAD

**Issue by Ramsin** [SadBatman/sumowallet#8]
Hello all, 

It would appear that the package identifier is the same for both Monerujo and the prebuilt betas of the Sumo Wallet for Android (understandably, since it's a fork)...

Here is the logcat output.

```
W/InstallAppProgress(11414): Replacing package:com.m2049r.xmrwallet
I/Finsky  ( 8216): [140] com.google.android.finsky.verifier.impl.bx.a(70): Skipping anti malware verification due to pre-check failure
I/Finsky  ( 8216): [1] com.google.android.finsky.verifier.impl.de.c(115): Verification complete: id=3, package_name=com.m2049r.xmrwallet
D/DefContainer(11439): Copying /storage/emulated/0/Download/app-debug.apk to base.apk
W/SurfaceFlinger(  371): couldn't log to binary event log: overflow.
W/PackageManager( 1160): Package com.m2049r.xmrwallet signatures do not match the previously installed version; ignoring!
D/InstallAppProgress(11414): Installation error code: -7
```

Please let me know if you want/need anything else from me. Take care, thank you for your work, and HAPPY NEW YEAR!!

**Comment by SadBatman** [comment]
Thanks for reporting. It seems I forgot to update the applicationId.

This is fixed in the following commit and I'll do a release later today:
https://github.com/SadBatman/sumowallet/commit/80181655154b3815feb51dbe44adce65c35420b9
